# Pandas for AI/ML – Conceptual & Technical Assessment

## Section A – Output Prediction

### Q1. Array Operations and Vectorization

#### Given Code

The following code creates a NumPy array and a Pandas Series containing the same values. The operation `* 2` is then applied to both structures.

```python
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)
```

#### Predicted Output

**NumPy Array:**

```text
[20 40 60]
```

**Pandas Series:**

```text
0    20
1    40
2    60
dtype: int64
```

#### Operation Insight

The multiplication by `2` is a **vectorized operation**. Instead of applying the multiplication separately to each value using a loop, NumPy and Pandas apply the operation directly to the complete data structure.

#### Key Observation

Both structures produce the same numerical values after multiplication. The main difference in the output is that the **Pandas Series keeps an index** (`0, 1, 2`) along with the values, while the NumPy array displays only the values.

#### Similarity

Both NumPy arrays and Pandas Series support **element-wise arithmetic operations**, so each value is multiplied by `2`.

#### Difference

A **NumPy array** is mainly used for efficient numerical and array-based computation, whereas a **Pandas Series** stores values together with an index, making it useful for working with labeled data.

#### Conclusion

The result shows how **vectorization allows the same operation to be performed efficiently across all elements without writing an explicit loop**.

## Q2. Boolean Filtering

### Given Code

The DataFrame contains student names and their marks. A **Boolean condition** is used to select only students whose marks are greater than or equal to `65`.

```python
df[df['Marks'] >= 65]
```

### Predicted Output

The condition `Marks >= 65` is satisfied by students **B, C, and D**.

```text
  Student  Marks
1       B     80
2       C     65
3       D     90
```

### Filtering Logic

The expression:

```python
df['Marks'] >= 65
```

creates a Boolean condition for each row. Pandas then keeps only the rows where the condition is `True`.

### Resulting Shape

The resulting DataFrame contains:

**3 rows × 2 columns**

So the shape is:

```text
(3, 2)
```

### Key Observation

The original DataFrame has four students, but Boolean filtering removes student **A** because their marks are `45`, which does not satisfy the condition `Marks >= 65`.

## Q3. Descriptive Statistics

### Given Code

The DataFrame contains five marks values. The code calculates three common descriptive statistics: **mean, maximum, and median**.

```python
df['Marks'].mean()
df['Marks'].max()
df['Marks'].median()
```

### Predicted Output

**Mean:**

```text
30.0
```

**Maximum:**

```text
50
```

**Median:**

```text
30.0
```

### Operation Insight

The `mean()` function calculates the average of all the marks, while `max()` returns the highest mark. The `median()` identifies the middle value after arranging the data in ascending order.

### Mean vs Median

For the values `10, 20, 30, 40, 50`, the middle value is `30`, so the median is `30.0`.

The mean is also `30.0` because the values are evenly distributed around the center.

### Key Observation

In this dataset, the **mean and median are equal**, because there is no extreme value pulling the average away from the middle of the data.

### Conclusion

Mean gives the overall average, while median gives the central value of an ordered dataset. The median can be especially useful when the data contains extreme values.

## Q4. Group-wise Analysis

### Given Code

The DataFrame contains employee departments and their salaries. The `groupby()` operation is used to separate the salary values based on each department and then calculate the average salary for each group.

```python
df.groupby('Department')['Salary'].mean()
```

### Predicted Output

```text
Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64
```

### Operation Insight

`groupby('Department')` creates separate groups for **HR** and **IT**. The `['Salary']` selection focuses only on the salary column, and `mean()` calculates the average salary within each department.

### Department-wise Calculation

**HR:**

```text
(30000 + 50000) / 2 = 40000
```

**IT:**

```text
(40000 + 60000) / 2 = 50000
```

### Key Observation

The result does not calculate one average for the complete DataFrame. Instead, the salaries are **grouped by department first**, and an average is calculated independently for each group.

### Conclusion

`groupby()` is useful for **group-wise analysis**, where the same calculation needs to be performed separately for different categories in a dataset.

## Q5. Pandas Correlation – Positive

### Given Code

The DataFrame contains the number of study hours and the corresponding marks. The `corr()` function is used to measure the relationship between these two numerical variables.

```python
df['Hours'].corr(df['Marks'])
```

### Predicted Output

```text
1.0
```

### Operation Insight

The `corr()` function calculates the **correlation coefficient** between `Hours` and `Marks`. The coefficient ranges from `-1` to `+1`.

### Interpretation

The correlation coefficient is **+1.0**, which indicates a **perfect positive correlation**.

As the number of study hours increases, the marks also increase in a consistent proportion.

### Key Observation

The values follow a perfectly increasing pattern:

```text
Hours  →  1, 2, 3, 4
Marks  → 20, 40, 60, 80
```

There is no deviation from the increasing relationship, which results in a correlation of `1.0`.

### Conclusion

A correlation of **+1.0** indicates that the two variables have a **perfect positive linear relationship** in this dataset.

## Q6. Pandas Correlation – Negative

### Given Code

The DataFrame contains **Price** and **Demand** values. The `corr()` function is used to measure how these two variables are related.

```python
df['Price'].corr(df['Demand'])
```

### Predicted Output

```text
-1.0
```

### Operation Insight

The `corr()` function returns a correlation coefficient between `-1` and `+1`. A negative value indicates that the two variables move in opposite directions.

### Interpretation

The correlation coefficient is **-1.0**, which indicates a **perfect negative correlation**.

As the **Price increases**, the **Demand decreases** consistently.

### Key Observation

The values follow a perfectly decreasing pattern:

```text
Price   → 10, 20, 30, 40
Demand  → 100, 80, 60, 40
```

Each increase in Price is accompanied by a corresponding decrease in Demand.

### Conclusion

The **negative sign** indicates an inverse relationship, while the value `1.0` in magnitude indicates that the relationship is **perfectly linear** in this dataset.

## Section B – Code Correction

### Q1. JSON and CSV

#### Problem

The CSV file already contains a **header row**, but `header=None` tells Pandas that the file has no header. As a result, the first row of the CSV can be treated as data incorrectly.

#### Corrected Code

```python
import pandas as pd

df = pd.read_csv("students.csv")
print(df)
```

#### Why This Correction Works

By removing `header=None`, Pandas uses the **first row of the CSV file as the column names**, which is the correct behaviour when the CSV already contains headers.

#### Expected Result

The DataFrame will have the CSV header names as its columns, instead of treating the first student record as the column names.

#### One-line Explanation

`pd.read_csv()` automatically uses the first row as the header when the CSV file contains column names.

## Q2. Data Analysis

### Problem

The objective is to display the **five highest salaries** from the DataFrame.

The given code sorts the `Salary` column in **ascending order** and then selects the first five rows. This gives the five lowest salaries instead.

### Corrected Code

```python
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

print(df.sort_values('Salary', ascending=False).head(5))
```

### Expected Output

```text
  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
2        A   30000
```

### Why This Correction Works

`ascending=False` arranges the salaries from **highest to lowest**. The `head(5)` operation then selects the first five records from that sorted result.

### One-line Explanation

The code uses **descending sorting followed by `head(5)`** to obtain the five highest salaries.

## Q3. Cleaning Data

### Problem

The `Marks` column contains a missing value. The `fillna()` operation calculates the mean and returns a new Series, but the result is **not assigned back to the DataFrame**.

### Corrected Code

```python
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print(df)
```

### Expected Output

```text
   Marks
0   70.0
1   80.0
2   90.0
```

### Why This Correction Works

The mean of the available marks is:

```text
(70 + 90) / 2 = 80
```

`fillna()` replaces the missing value with `80`, and assigning the result back to `df['Marks']` updates the DataFrame.

### One-line Explanation

The corrected code **assigns the result of `fillna()` back to the `Marks` column**, so the missing value is actually replaced.

## Q4. Correlation

### Problem

The objective is to calculate the correlation between `Hours` and `Marks`.

The given `df.corr('Hours', 'Marks')` is incorrect because `DataFrame.corr()` does not take column names in that form. The columns should be selected first and then their correlation should be calculated.

### Corrected Code

```python
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))
```

### Expected Output

```text
1.0
```

### Why This Correction Works

`df['Hours']` and `df['Marks']` select the two required Series. The `corr()` method then calculates the correlation between these two columns.

### One-line Explanation

The corrected code calculates the correlation by calling `corr()` directly between the `Hours` and `Marks` Series.

# Section C – Edge Cases

## Q1. NumPy Broadcasting

### Given Code

The two NumPy arrays have different shapes: `a` has shape `(3, 1)` and `b` has shape `(1, 3)`. NumPy uses **broadcasting** to make their shapes compatible for element-wise addition.

### Array Shapes Before Addition

```text
a → (3, 1)
b → (1, 3)
```

### Expected Output

```text
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
```

### Operation Insight

Broadcasting allows NumPy to virtually expand the smaller dimensions so that the two arrays can be added without manually creating a larger array.

The `(3, 1)` array is matched with the `(1, 3)` array, producing a final shape of `(3, 3)`.

### Why the Result Is 3 × 3

The values in `a` are arranged vertically:

```text
10
20
30
```

The values in `b` are arranged horizontally:

```text
1  2  3
```

Broadcasting combines each value from `a` with every value from `b`.

### Edge Case: If `b = np.array([1, 2])`

The addition still works because NumPy can broadcast the shape `(2,)` across the second dimension of the `(3, 1)` array.

The resulting shape becomes `(3, 2)`:

```text
[[11 12]
 [21 22]
 [31 32]]

### Conclusion

Broadcasting allows arrays with compatible shapes to participate in element-wise operations without explicitly reshaping or copying the data.

In [18]:
import numpy as np

# 'a' is arranged vertically with 3 rows and 1 column.
# 'b' is arranged horizontally with 1 row and 3 columns.
# These shapes allow NumPy to use broadcasting during addition.
a = np.array([[10],
              [20],
              [30]])

b = np.array([[1, 2, 3]])

# Broadcasting expands the two arrays virtually to the same
# shape and performs element-wise addition.
result = a + b

print("Array a:")
print(a)

print("\nShape of a:")
print(a.shape)

print("\nArray b:")
print(b)

print("\nShape of b:")
print(b.shape)

print("\nResult after broadcasting and addition:")
print(result)

print("\nShape of the result:")
print(result.shape)

# This case is intentionally tested separately because
# the new shape cannot be broadcast with a (3, 1) array.
b_invalid = np.array([1, 2])

print("\nTrying an incompatible shape:")

try:
    print(a + b_invalid)
except ValueError as error:
    print("ValueError:", error)

Array a:
[[10]
 [20]
 [30]]

Shape of a:
(3, 1)

Array b:
[[1 2 3]]

Shape of b:
(1, 3)

Result after broadcasting and addition:
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Shape of the result:
(3, 3)

Trying an incompatible shape:
[[11 12]
 [21 22]
 [31 32]]

## Q2. CSV Parsing, Missing Values and Date Handling

### Given Dataset

The CSV contains a quoted comma inside the `Name` column, missing marks, and dates written in different formats.

### Parsing Observation

The value `"Asha, R"` contains a comma, but because the name is enclosed in double quotes, Pandas treats it as **one field** instead of splitting it into two columns.

### Potential Issues

The `Date` column contains different date formats, so it should be converted into a consistent datetime format.

The `Marks` column contains both a blank value and `"NA"`. These values should be investigated before treating them as missing marks.

### Robust Approach

The data should be loaded normally, the `Date` column should be converted using `pd.to_datetime()`, and the `Marks` column should be converted to numeric values so that invalid or missing entries can be identified.

### Why `"NA"` Needs Investigation

`"NA"` may represent a missing mark, but it could also be a value used by the original data source for another reason. It should therefore be investigated before automatically treating it as a missing value.

### Conclusion

Correct CSV parsing is important because an incorrectly parsed column can change the structure of the DataFrame and lead to incorrect analysis.

In [19]:
import pandas as pd

# Keep values such as "NA" unchanged initially so that
# their meaning can be investigated before treating them as missing.
df = pd.read_csv("students.csv", keep_default_na=False)

print("Original DataFrame:")
display(df)

print("\nOriginal Data Types:")
display(df.dtypes)

# Convert dates into a consistent datetime representation.
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")

# Convert Marks to numeric values.
# Invalid entries such as "NA" become missing values (NaN).
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

print("\nDataFrame after cleaning Date and Marks:")
display(df)

print("\nUpdated Data Types:")
display(df.dtypes)

Original DataFrame:

    ID     Name        Date Marks
0  101  Asha, R  2026-09-01    80
1  102     Ravi  01/09/2026
2  103     Neha  2026-09-03    NA

Original Data Types:

ID       int64
Name       str
Date       str
Marks      str
dtype: object

DataFrame after cleaning Date and Marks:

    ID     Name       Date  Marks
0  101  Asha, R 2026-01-09   80.0
1  102     Ravi        NaT    NaN
2  103     Neha 2026-03-09    NaN

Updated Data Types:

ID                int64
Name                str
Date     datetime64[us]
Marks           float64
dtype: object

## Q3. Salary Outlier and Robust Statistics

### Given Data

The salary column contains three values in a relatively small range and one extremely large value. This makes it important to compare the **mean** and **median** before deciding which statistic represents a typical salary.

### Predicted Output

**Mean:**

```text
2522500.0
```

**Median:**

```text
32500.0
```

### Effect of the Outlier

The salary `10000000` is much larger than the other salaries. Since the mean uses every value in the calculation, this extreme value pulls the mean strongly upward.

The median is much less affected because it depends on the middle position after sorting the values.

### Better Representation of a Typical Salary

For this dataset, the **median** better represents a typical employee salary because it is not strongly affected by the extreme salary value.

### Important Observation

The extreme value should not be removed automatically. It may be a genuine salary belonging to a senior employee, or it could be a data-entry error.

Therefore, the record should be **investigated before removing it**.

### Conclusion

The mean is sensitive to extreme values, while the median is more robust when the dataset contains an outlier.

In [20]:
import pandas as pd

# Create the salary data so we can compare the effect
# of the unusually large salary on mean and median.
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Salary": [25000, 30000, 35000, 10000000]
})

print("Salary Data:")
display(df)

# Mean considers every salary, so the extreme value
# has a strong effect on the final average.
mean_salary = df["Salary"].mean()

# Median uses the middle position after sorting,
# making it less sensitive to an extreme value.
median_salary = df["Salary"].median()

print("\nMean Salary:", mean_salary)
print("Median Salary:", median_salary)

# Identify the employee record with the highest salary
# so the unusual value can be investigated.
highest_salary = df.iloc[df["Salary"].to_numpy().argmax()]

print("\nHighest Salary Record:")
print(highest_salary)

Salary Data:

  Employee    Salary
0        A     25000
1        B     30000
2        C     35000
3        D  10000000

Mean Salary: 2522500.0
Median Salary: 32500.0

Highest Salary Record:
Employee           D
Salary      10000000
Name: 3, dtype: object

# Section D – Scenario-Based Problems

## Q1. Student Assessment Data Cleaning

### Problem Understanding

The dataset contains different types of data-quality issues such as inconsistent department names, duplicate records, missing marks, text values in the `Marks` column, and marks outside the valid range.

The cleaning process should handle these issues step by step while preserving useful information for investigation.

### Cleaning Sequence

1. Load and inspect the dataset.
2. Standardize department names.
3. Identify and remove exact duplicate records.
4. Preserve and investigate the original `Marks` entries.
5. Convert the `Marks` column into a numeric format.
6. Distinguish between absent students and marks that have not been entered.
7. Identify marks outside the valid `0–100` range.
8. Display the cleaned DataFrame.
9. Report the cleaning results.

### Handling Missing Marks

A blank mark, `Absent`, and `NA` should not automatically be treated as the same situation.

A blank value can indicate that the mark has not been entered, while `Absent` indicates that the student did not attend the assessment. The `NA` value should also be investigated before deciding how it should be treated.

### Risk of Deleting Missing Values

Deleting all records with missing marks without investigating them can remove valid student information and hide the actual reason why the data is missing.

### Handling Invalid Marks

Marks outside the valid range of `0–100` should be identified and investigated before deciding whether they should be corrected or removed.

For example, a mark of `105` may indicate a data-entry error rather than a valid assessment result.

In [21]:
import pandas as pd

# Load the dataset so that the original records can be
# inspected before making any cleaning changes.
df = pd.read_csv("student_assessment_dirty.csv")

print("===== INITIAL DATASET =====")
display(df)

print("\n===== FIRST 5 RECORDS =====")
display(df.head())

print("\n===== DATASET INFORMATION =====")
df.info()

print("\n===== MISSING VALUES =====")
display(df.isnull().sum().to_frame("Missing Count"))


# Standardize department names so that different spellings
# such as IT, it and I.T. are represented consistently.
df["Department"] = (
    df["Department"]
    .str.strip()
    .str.upper()
    .replace({
        "I.T.": "IT"
    })
)

print("\n===== STANDARDIZED DEPARTMENTS =====")
display(df[["Student_ID", "Department"]].drop_duplicates())


# Identify exact duplicate records before removing them.
duplicate_count = df.duplicated().sum()

print("\n===== EXACT DUPLICATE RECORDS =====")
display(df[df.duplicated(keep=False)])

print("Number of exact duplicate records:", duplicate_count)

# Remove only exact duplicate records.
df = df.drop_duplicates()


# Preserve the original Marks values before converting them.
# This allows us to distinguish Absent, NA and blank entries.
df["Marks_Status"] = df["Marks"].astype("string").str.strip()

df["Marks_Status"] = df["Marks_Status"].replace({
    "Absent": "Absent",
    "NA": "Not Available"
})

# A blank value means the mark has not been entered.
df.loc[
    df["Marks_Status"].isna() | (df["Marks_Status"] == ""),
    "Marks_Status"
] = "Not Entered"


print("\n===== MARKS STATUS BEFORE NUMERIC CONVERSION =====")
display(
    df[
        ["Student_ID", "Student_Name", "Marks", "Marks_Status"]
    ]
)


# Remove the word "marks" from values such as "88 marks".
# The remaining values can then be converted into numbers.
df["Marks"] = (
    df["Marks"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s*marks\s*$", "", regex=True, case=False)
)

# Convert valid numeric values into numbers.
# Values such as Absent and NA become NaN during conversion.
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")


print("\n===== MISSING MARKS AFTER CONVERSION =====")
display(
    df[
        df["Marks"].isna()
    ][
        ["Student_ID", "Student_Name", "Marks_Status", "Marks"]
    ]
)


# Identify marks outside the valid assessment range of 0–100.
invalid_marks = (
    df["Marks"].notna()
    & ~df["Marks"].between(0, 100)
)

print("\n===== INVALID MARKS OUTSIDE 0–100 =====")
display(
    df.loc[
        invalid_marks,
        ["Student_ID", "Student_Name", "Marks"]
    ]
)


# Count the results required for the final report.
missing_count = df["Marks"].isna().sum()
invalid_count = invalid_marks.sum()


print("\n===== CLEANED DATASET =====")
display(df)


# Create a simple summary table for the final cleaning report.
report = pd.DataFrame({
    "Measure": [
        "Records removed as exact duplicates",
        "Missing marks remaining",
        "Invalid marks identified"
    ],
    "Count": [
        duplicate_count,
        missing_count,
        invalid_count
    ]
})

print("\n===== CLEANING REPORT =====")
display(report)

===== INITIAL DATASET =====

   Student_ID Student_Name Department Assessment     Marks
0        S101         Asha         IT     Python        85
1        S102         Ravi         it     Python        78
2        S103         Neha       I.T.     Python        92
3        S104        Karan         HR     Python       NaN
4        S105        Meera         HR     Python    Absent
5        S106        Arjun    Finance     Python         0
6        S107        Priya    finance     Python        67
7        S108        Rahul         IT     Python        75
8        S102         Ravi         it     Python        78
9        S109        Sneha       I.T.     Python       NaN
10       S110        Varun         HR     Python  88 marks
11       S111         Diya    Finance     Python        91
12       S112         Aman         IT     Python       NaN
13       S113        Nisha         HR     Python        64
14       S114        Kabir    Finance     Python       105

===== FIRST 5 RECORDS =====

  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

===== DATASET INFORMATION =====
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str
 1   Student_Name  15 non-null     str
 2   Department    15 non-null     str
 3   Assessment    15 non-null     str
 4   Marks         12 non-null     str
dtypes: str(5)
memory usage: 732.0 bytes

===== MISSING VALUES =====

              Missing Count
Student_ID                0
Student_Name              0
Department                0
Assessment                0
Marks                     3

===== STANDARDIZED DEPARTMENTS =====

   Student_ID Department
0        S101         IT
1        S102         IT
2        S103         IT
3        S104         HR
4        S105         HR
5        S106    FINANCE
6        S107    FINANCE
7        S108         IT
9        S109         IT
10       S110         HR
11       S111    FINANCE
12       S112         IT
13       S113         HR
14       S114    FINANCE

===== EXACT DUPLICATE RECORDS =====

  Student_ID Student_Name Department Assessment Marks
1       S102         Ravi         IT     Python    78
8       S102         Ravi         IT     Python    78

Number of exact duplicate records: 1

===== MARKS STATUS BEFORE NUMERIC CONVERSION =====

   Student_ID Student_Name     Marks Marks_Status
0        S101         Asha        85           85
1        S102         Ravi        78           78
2        S103         Neha        92           92
3        S104        Karan       NaN  Not Entered
4        S105        Meera    Absent       Absent
5        S106        Arjun         0            0
6        S107        Priya        67           67
7        S108        Rahul        75           75
9        S109        Sneha       NaN  Not Entered
10       S110        Varun  88 marks     88 marks
11       S111         Diya        91           91
12       S112         Aman       NaN  Not Entered
13       S113        Nisha        64           64
14       S114        Kabir       105          105

===== MISSING MARKS AFTER CONVERSION =====

   Student_ID Student_Name Marks_Status  Marks
3        S104        Karan  Not Entered   <NA>
4        S105        Meera       Absent   <NA>
9        S109        Sneha  Not Entered   <NA>
12       S112         Aman  Not Entered   <NA>

===== INVALID MARKS OUTSIDE 0–100 =====

   Student_ID Student_Name  Marks
14       S114        Kabir    105

===== CLEANED DATASET =====

   Student_ID Student_Name Department Assessment  Marks Marks_Status
0        S101         Asha         IT     Python     85           85
1        S102         Ravi         IT     Python     78           78
2        S103         Neha         IT     Python     92           92
3        S104        Karan         HR     Python   <NA>  Not Entered
4        S105        Meera         HR     Python   <NA>       Absent
5        S106        Arjun    FINANCE     Python      0            0
6        S107        Priya    FINANCE     Python     67           67
7        S108        Rahul         IT     Python     75           75
9        S109        Sneha         IT     Python   <NA>  Not Entered
10       S110        Varun         HR     Python     88     88 marks
11       S111         Diya    FINANCE     Python     91           91
12       S112         Aman         IT     Python   <NA>  Not Entered
13       S113        Nisha         HR     Python     64           64
14       S114        Kabir    FINANCE     Python    105          105

===== CLEANING REPORT =====

                               Measure  Count
0  Records removed as exact duplicates      1
1              Missing marks remaining      4
2             Invalid marks identified      1